repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks.git
      rev: v4.4.0
      hooks:
      -   id: trailing-whitespace
          name: Check for trailing whitespace
      -   id: end-of-file-fixer
          name: Check for newlines at end of files
      -   id: mixed-line-ending
          name: Check mixed line endings between Windows and Unix
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.4.1'
      hooks:
      -   id: mypy
          name: Run Mypy static type checker
  -   repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
      -   id: black
          name: Run Black code formatter
  -   repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
      -   id: isort
          args: ["--profile", "black"]
          name: Run Isort import formatter
  -   repo: local
      hooks:
        - id: unit-tests
          name: Run unit tests
          entry: bash -c 'pytest tests/unit'
          language: system
